server:
  port: 8080

spring:
  application:
    name: reactive-bingo
  data:
    mongodb:
      uri: mongodb+srv://geraldo:Ua7TtFKBQ1UcgCKc@cluster0.accnknh.mongodb.net/dio
      database: dio

app:
  version: ^project.version^