server:
  port: 8080

spring:
  application:
    name: reactive-bingo
  data:
    mongodb:
      uri: mongodb+srv://geraldo:<password>@cluster0.accnknh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: dio

app:
  version: ^project.version^